export const SERVICES_SELECT_SERVICE = 'SERVICES:SELECT_SERVICE';
export const SERVICES_DESELECT_SERVICE = 'SERVICES:DESELECT_SERVICE';

export const EMPLOYEE_SELECT_EMPLOYEE = 'EMPLOYEE:SELECT_EMPLOYEE';

export const APP_INFO_SET_APP_INFO = 'APP_INFO:SET_APP_INFO';

export const TIME_LIST_SET_DATA = 'TIME_LIST:SET_DATA';
export const TIME_LIST_SET_SELECTED_TIME = 'TIME_LIST:SET_SELECTED_TIME';

export const BOOKING_DATE_SET_DATE = "BOOKING_DATE:SET_DATE";